project:
  type: website
  render:
    - "*.qmd"
    - "*.md"

website:
  title: "Washington S. da Silva"
  site-url: "https://mariecurie.com"
  navbar:
    background: "#000000"
    left:
      - href: publications/index.qmd
        text: Publications
      - href: blog/index.qmd
        text: Blog
      - href: teaching/index.qmd
        text: Teaching
      - href: projects/index.qmd
        text: Projects
      - href: tutorials/index.qmd
        text: Tutorials
#      - href: talks/index.qmd
#        text: Talks
      - href: about/index.qmd
        text: About
  page-footer:
    left: "Copyright 2023, Washington Santos da Silva"
    right:
      - icon: github
        href: https://github.com/washingtonsilva
      - icon: linkedin
        href: https://www.linkedin.com/in/washingtonssilva/
    background: "#000000"

date-format: "D MMMM YYYY"

format:
  html:
    theme: tango
    css: styles.css
    toc: true
    html-math-method: katex
    include-in-header:
      file: header.html

